/* Generated By:JavaCC: Do not edit this line. MiniRustConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniRustConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int FN = 6;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int PRINTLN = 8;
  /** RegularExpression Id. */
  int READFLOAT = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int APAR = 13;
  /** RegularExpression Id. */
  int FPAR = 14;
  /** RegularExpression Id. */
  int BEGIN = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int SEMICO = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int SUM = 20;
  /** RegularExpression Id. */
  int SUB = 21;
  /** RegularExpression Id. */
  int MULT = 22;
  /** RegularExpression Id. */
  int DIV = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int LESSTHEN = 26;
  /** RegularExpression Id. */
  int MORETHEN = 27;
  /** RegularExpression Id. */
  int EQUAL = 28;
  /** RegularExpression Id. */
  int ATRIB = 29;
  /** RegularExpression Id. */
  int FLOAT32 = 30;
  /** RegularExpression Id. */
  int VOID = 31;
  /** RegularExpression Id. */
  int BOOL = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int ARROW = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int NUM = 38;
  /** RegularExpression Id. */
  int ID = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"fn\"",
    "\"let\"",
    "\"println!\"",
    "\"read_float\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"=\"",
    "\"f32\"",
    "\"void\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"->\"",
    "<DIGIT>",
    "<LETTER>",
    "<NUM>",
    "<ID>",
  };

}
